version: '1.0.{build}'
image: Visual Studio 2017
branches:
  only:
  - master
init:
  # Best practice (Windows line endings different to Unix/Linux)
  - cmd: git config --global core.autocrlf true
install:
  - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v4.0.0/nuget.exe
before_build:
  # Display .NET Core version
  - cmd: dotnet --version
  # Display minimal restore text
  - cmd: dotnet restore ./src/Threenine.Data.csproj --verbosity m
build_script:
    - cmd: dotnet build ./src/Threenine.Data.csproj -c Release
    - cmd: dotnet pack  -c Release /p:PackageVersion=1.1.2 
test_script:
    - cmd: dotnet test "./Tests/Threenine.Data.Tests/Threenine.Data.Tests.csproj" -c Release
artifacts:
- path: ./src/bin/Release/*.nupkg
  name: NuGet

de
- provider: NuGet
  server:  https://www.nuget.org/
  api_key:
    secure: mf21OOa1QnyeVLSIaFDmmEj63k0aZ8NkhKIa7YspDZtCMRWfcHYpF/GXnJn3lDv4
 